print(f"Quiz 1. 반복문을 이용한 별찍기")
print(f"변수 n에 입력된 수 만큼 '*'로 이뤄진 도형 찍기")
print(f"ex ) n = 3")
print(f"정사각형 : ")
print(f"	***")
print(f"	***")
print(f"	***")

print(f"역직각삼각형 : ")
print(f"	***")
print(f"	**")
print(f"	*\n")
print(f"n = 3")
print(f"정사각형 별찍기 로직 : \n")

print(f"역직각삼각형 별찍기 로직 : \n")
